apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Ti
  storageClassName: example-storage-class
  claimRef:
    namespace: default
    name: gcs-fuse-csi-static-pvc
  mountOptions:
    # Specify the name of the directory within the bucket which you want to mount
    - only-dir=invoices
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: BUCKET_NAME
    volumeAttributes:
      gcsfuseLoggingSeverity: warning

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-csi-static-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: gcs-fuse-csi-pv
  storageClassName: example-storage-class