apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv-fuse2
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  storageClassName: fuse2-storage-class
  claimRef:
    namespace: dev
    name: gcs-fuse2-csi-static-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: BUCKET_NAME
    volumeAttributes:
      gcsfuseLoggingSeverity: warning

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse2-csi-static-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: gcs-fuse-csi-pv-fuse2
  storageClassName: fuse2-storage-class